USE library;

/*4*/
SELECT TITLE, AUTHOR_CODE
FROM BOOK
WHERE AUTHOR_CODE IS NULL
;

/*5*/
SELECT B.TITLE, A.NAME
FROM BOOK B LEFT JOIN AUTHOR A
ON A.AUTHOR_CODE = B.AUTHOR_CODE
;

/*6*/
SELECT B.TITLE, CONCAT(A.NAME, ' ', A.SURNAMES) AS COMPLETE_NAME
FROM BOOK B LEFT JOIN AUTHOR A
ON A.AUTHOR_CODE = B.AUTHOR_CODE
;

/*7*/
SELECT B.TITLE, CONCAT(A.NAME, ' ', A.SURNAMES) AS COMPLETE_NAME
FROM AUTHOR A
LEFT JOIN
BOOK B USING(AUTHOR_CODE)
WHERE B.AUTHOR_CODE IS NULL
;

/*8*/
SELECT DISTINCT CONCAT(M.NAME," ",M.SURNAMES) AS MEMBER
FROM MEMBER M 
LEFT JOIN BORROW B 
USING (MEMBER_CODE)
WHERE B.MEMBER_CODE IS NULL;

/*9*/
 SELECT 
    GENRE.GENRE_CODE, GENRE.NAME as GENRE_NAME, NULL as BOOK_CODE, NULL as BOOK_TITLE
FROM
    GENRE LEFT JOIN GENREBOOK 
ON GENRE.GENRE_CODE = GENREBOOK.GENRE_CODE
WHERE
    GENREBOOK.GENRE_CODE IS NULL 
UNION 
SELECT 
   NULL, NULL, BOOK.BOOK_CODE, BOOK.TITLE
FROM BOOK LEFT JOIN GENREBOOK ON GENREBOOK.BOOK_CODE = BOOK.BOOK_CODE
WHERE
    GENREBOOK.BOOK_CODE IS NULL; 

 

/*10*/
SELECT P.NAME, B.PUBLISHER_CODE
FROM 
PUBLISHER P LEFT JOIN BOOK B
USING (PUBLISHER_CODE)
WHERE B.PUBLISHER_CODE IS NULL
;

SELECT *
FROM BOOK B
WHERE B.PUBLISHER_CODE = (
SELECT DISTINCT P.PUBLISHER_CODE
FROM PUBLISHER P 
WHERE P.NAME = 'EUMO')
;

/*11*/
SELECT b.title as 'Book Title'
FROM BOOK b LEFT JOIN COPY c USING(BOOK_CODE)
WHERE c.COPY_CODE IS NULL;

/*12 - Name of the authors distinct to NOAH GORDON 
who have written any history book. (MULTIPLES INNER JOIN)
*/
SELECT * 
FROM GENRE
;

SELECT CONCAT(A.NAME, " ", A.SURNAMES) AS NOMBRE_COMPLETO, G.NAME
FROM AUTHOR A
INNER JOIN GENRE G
WHERE G.NAME = 'HISTORIA'
AND A.NAME != 'NOAH' 
AND A.SURNAMES != 'GORDON'
;

SELECT CONCAT(a.name, ' ', a.surnames) AS 'Name'
FROM AUTHOR a  JOIN BOOK b USING (author_code)
   	  JOIN GENREBOOK gb USING (book_code)
    	 JOIN GENRE g USING (genre_code)
WHERE CONCAT(a.name, ' ', a.surnames) != 'Noah Gordon'
   	 AND g.name = 'HISTORIA';
     
/*13 - Full name of the members who live in the same city as 
the member with code 1. (SUBQUERY WHERE OR SUBQUERY FROM)*/
SELECT CONCAT(M.NAME, " ", M.SURNAMES) AS 'FULL NAME',  M.CITY
FROM MEMBER M 
WHERE M.CITY = (
	SELECT M2.CITY
    FROM MEMBER M2
    WHERE M2.MEMBER_CODE = '1')
;

/*14 - Title of all books published by the same publisher as 
the book ‘EL MEDICO’. (SUBQUERY WHERE OR SUBQUERY FROM
 + INNER JOIN)*/
 SELECT B.TITLE
 FROM BOOK B
 WHERE B.PUBLISHER_CODE = (
	SELECT B2.PUBLISHER_CODE
    FROM BOOK B2 
    WHERE B2.TITLE = "EL MEDICO")
;

/*15 - Title of all books published by the same author as the book 
‘EL MEDICO’.*/
 SELECT B.TITLE
 FROM BOOK B
 WHERE B.AUTHOR_CODE = (
	SELECT B2.AUTHOR_CODE
    FROM BOOK B2 
    WHERE B2.TITLE = "EL MEDICO")
;

/*16 - Title of the books that belong to any genre to which 
the book ‘EL MEDICO’ belongs to*/
SELECT BOOK.TITLE
FROM BOOK 
JOIN GENREBOOK GR USING (BOOK_CODE)
WHERE GR.GENRE_CODE IN (
	SELECT GENRE_CODE
    FROM GENREBOOK
    WHERE BOOK_CODE IN (
		SELECT B2.BOOK_CODE
        FROM BOOK B2
        WHERE B2.TITLE = 'EL MEDICO'
        )
)
;

/*2.1 - Author's name and the number of books written by them.*/
SELECT A.NAME, COUNT(B.BOOK_CODE) AS "TOTAL BOOKS"
FROM AUTHOR A JOIN BOOK B USING(AUTHOR_CODE)
GROUP BY A.AUTHOR_CODE
;

SELECT * 
FROM MEMBER
;

/*2.2 - Books title and the amount of copies of each book. */
SELECT B.TITLE, COUNT(C.COPY_CODE) AS "TOTAL COPIES"
FROM BOOK B JOIN COPY C USING(BOOK_CODE)
GROUP BY C.BOOK_CODE
;

/*2.2 - Genres name and the number of books of that genre.*/
SELECT G.NAME, COUNT(GR.BOOK_CODE) AS "TOTAL BOOKS"
FROM GENRE G JOIN GENREBOOK GR USING(GENRE_CODE)
GROUP BY G.GENRE_CODE;



/*3.1 - List of members that have borrowed books more than 3 times.*/
SELECT M.NAME
FROM MEMBER M INNER JOIN BORROW B USING(MEMBER_CODE)
GROUP BY M.MEMBER_CODE
HAVING COUNT(B.MEMBER_CODE) > 3
;

/*3.2 - List of members that have more than one book currently
borrowed (not returned yet).*/
SELECT M.NAME 
FROM MEMBER M INNER JOIN BORROW B USING(MEMBER_CODE)
WHERE B.RETURN_DATE IS NULL
GROUP BY M.MEMBER_CODE
HAVING COUNT(B.MEMBER_CODE) > 1
;

SELECT * 
FROM COPY
;

SELECT * 
FROM AUTHOR
;
/*3.3 - Amount of copies of every book published by ‘PLANETA’. 
Return the title, language, author, name and amount of copies 
by book, ordered by amount of copies and author name.
Discard all books having less than 2 copies.*/
SELECT B.TITLE, B.LANGUAGE, A.NAME, 
